vich_uploader:
    db_driver: orm

    mappings:
       coupart:
           uri_prefix: /images/coupart
           upload_destination: '%kernel.project_dir%/public/images/coupart'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
